### ISSUE TITLE
ImportError: cannot import name 'non_x86_linux_machines'

### ISSUE THREAD

**Issue by ifmaq1** [fredzzhang/pocket#52]
I have followed all the steps to install pocket.
it gives me error on the following line

**conda develop pocket**

**(pocket) $ conda develop pocket**
Traceback (most recent call last):
  File "/home/anaconda3/bin/conda-develop", line 7, in <module>
    from conda_build.cli.main_develop import main
  File "/home/anaconda3/lib/python3.6/site-packages/conda_build/cli/main_develop.py", line 12, in <module>
    from conda_build.conda_interface import ArgumentParser, add_parser_prefix, get_prefix
  **File "/home/anaconda3/lib/python3.6/site-packages/conda_build/conda_interface.py", line 206, in <module>
    from conda.base.context import non_x86_linux_machines
ImportError: cannot import name 'non_x86_linux_machines'**

### do you know the possible reason?

only one thing is different on my system.It has CUDA 10.1 so i install **pytorch torchvision**  using pip and cuda 10.1

**Comment by fredzzhang** [comment]
Hi @ifmaq1 ,

That seems like a problem with conda. I'm not sure what is wrong here but the point of running `conda develop pocket` is to add the library in the python search path. Alternatively, you can manually add it in your `PYTHONPATH `.

Cheers,
Fred.
